### ISSUE TITLE
Where is cc_ibiza_sunset_spec.bsdf ?

### ISSUE THREAD

**Issue by vlisivka** [rgl-epfl/brdf-loader#2]
I'm trying to run sample code, but I cannot find `cc_ibiza_sunset_spec.bsdf` file to load.
Where to find this file?

**Comment by jdupuy** [comment]
Ah yes, we removed the dataset from the repo to keep it lightweight.
You should download the bsdf file directly from the database website here: http://rgl.epfl.ch/materials
